partition: XYZ
rd_id: 20
vlans:
  - name: "VLAN_X"
    tag: 123
    interface: '1.1'
  - name: "VLAN_Y"
    tag: 321
    interface: '1.1'
self_ips:
  - name: 'X-SelfIP'
    address: '192.168.33.10'
    netmask: '255.255.255.0'
    vlan: 'VLAN_X'
    allow_service: 'default'
  - name: 'Y-SelfIP'
    address: '192.168.34.10'
    netmask: '255.255.255.0'
    vlan: 'VLAN_Y'
    allow_service: 'default'
nodes:
  - name: "NODE_ABC_AAAAAAA_192.168.34.200"
    address: "192.168.34.200"
    port: 80
  - name: "NODE_ABC_AAAAAAA_192.168.34.201"
    address: "192.168.34.201"
    port: 8080
pool_name: "POOL_DC1ABC_80"
vs:
  name: "VS_ABC_443"
  destination: "192.168.33.70"
  port: 443
probe:
  name: "MON_ABC_HTTP_80"
  send: "GET /some_uri \r\n"
  receive: "OK"
  port: "80"